### ISSUE TITLE
Build Error Ubuntu 16.04

### ISSUE THREAD

**Issue by MCrypto** [VictoriumProject/go-victorium#1]
i keep getting this error:

>  go get -v github.com/VictoriumProject/go-victorium/...
github.com/VictoriumProject/go-victorium (download)
> runtime
> '# runtime
> /usr/local/go/src/runtime/mstkbar.go:151:10: debug.gcstackbarrieroff undefined (type struct { allocfreetrace int32; cgocheck int32; efence int32; gccheckmark int32; gcpacertrace int32; gcshrinkstackoff int32; gcrescanstacks int32; gcstoptheworld int32; gctrace int32; invalidptr int32; sbrk int32; scavenge int32; scheddetail int32; schedtrace int32 } has no field or method gcstackbarrieroff)
> /usr/local/go/src/runtime/mstkbar.go:162:24: division by zero
> /usr/local/go/src/runtime/mstkbar.go:162:43: invalid expression unsafe.Sizeof(composite literal)
> /usr/local/go/src/runtime/mstkbar.go:162:44: undefined: stkbar
> /usr/local/go/src/runtime/mstkbar.go:212:4: gp.stkbar undefined (type *g has no field or method stkbar)
> /usr/local/go/src/runtime/mstkbar.go:213:15: gp.stkbar undefined (type *g has no field or method stkbar)
> /usr/local/go/src/runtime/mstkbar.go:216:23: undefined: stackBarrierPC
> /usr/local/go/src/runtime/mstkbar.go:226:28: gp.stkbarPos undefined (type *g has no field or method stkbarPos)
> /usr/local/go/src/runtime/mstkbar.go:227:19: gp.stkbarPos undefined (type *g has no field or method stkbarPos)
> /usr/local/go/src/runtime/mstkbar.go:248:41: undefined: stkbar
> /usr/local/go/src/runtime/mstkbar.go:227:19: too many errors

im using go 1.9.2

> go version go1.9.2 linux/amd64

?

**Comment by Victorium-org** [comment]
Hello, you have the wrong installation go

> You unpacked the .tar.gz file in a directory that held an earlier 
> installation of Go.  Do not do that.  Only unpack the .tar.gz file in 
> a completely empty directory. 

https://groups.google.com/forum/#!topic/golang-nuts/wAYxijyyL5U

**Comment by MCrypto** [comment]
thank you :) that solved it!

deleted the src/local/go folder and re-installed go 1.9.2 and all worked fine :)
